name: dim_deepconvlstm
dataset_name: wear
has_null: True
anno_json: [
  'data/wear/annotations/loso_sbj_0.json',
  'data/wear/annotations/loso_sbj_1.json',
  'data/wear/annotations/loso_sbj_2.json',
  'data/wear/annotations/loso_sbj_3.json',
  'data/wear/annotations/loso_sbj_4.json',
  'data/wear/annotations/loso_sbj_5.json',
  'data/wear/annotations/loso_sbj_6.json',
  'data/wear/annotations/loso_sbj_7.json',
  'data/wear/annotations/loso_sbj_8.json',
  'data/wear/annotations/loso_sbj_9.json',
  'data/wear/annotations/loso_sbj_10.json',
  'data/wear/annotations/loso_sbj_11.json',
  'data/wear/annotations/loso_sbj_12.json',
  'data/wear/annotations/loso_sbj_13.json',
  'data/wear/annotations/loso_sbj_14.json',
  'data/wear/annotations/loso_sbj_15.json',
  'data/wear/annotations/loso_sbj_16.json',
  'data/wear/annotations/loso_sbj_17.json',
]
dataset: {
  sens_folder: ./data/wear/raw/inertial,
  vid_folder: ./data/wear/raw/ego,
  conv3d_folder: ./data/wear/processed/conv3d_features/24_frames_12_stride,
  raft_folder: ./data/wear/processed/raft_features/24_frames_12_stride, 
  dino_folder: ./data/wear/processed/dino_features/24_frames_12_stride_avg_pool, 
  clip_folder: ./data/wear/processed/clip_features/24_frames_12_stride_avg_pool,  
  input_dim: 12,
  conv3d_dim: 1024,
  raft_dim: 1024,
  dino_dim: 1024,
  clip_dim: 768,
  fps: 12,
  clip_size: 24,
  stride: 12,
  nb_classes: 19,
  sampling_rate: 50,
  t_window_size: 50,
  t_window_overlap: 50,
  c_window_size: 100,
  c_window_overlap: 50,
  tiou_thresholds: [0.3, 0.4, 0.5, 0.6, 0.7]
}
clustering: {
  clustering_method: 'gmm',
  nb_clusters: 100,
  outlier_removal: False,
  outlier_eps: -1,
  dim_reduction: False,
  thresholding: False,
  threshold_dist: 0.5,
  sampling_strategy: 'distance',
  nb_samples: 1
}
model: {
  conv_kernels: 64,
  conv_kernel_size: 9,
  lstm_units: 128,
  lstm_layers: 1,
  dropout: 0.5
}
train_cfg: {
  supervision_type: 'full_supervision',
  loss_type: 'cross_entropy',
  label_smoothing: 0.0,
  lr: 0.0001,
  lr_decay: 0.9,
  lr_step: 10,
  epochs: 30,
  weight_decay: 0.000001,
  weight_init: 'xavier_normal',
  weighted_loss: True,
}
loader: {
  batch_size: 100,
  shuffle: False
}